/**
 * middleware/apiKey.js
 *
 * Security fixes:
 *  1. NoSQL injection: reject any non-string API key (object operators like
 *     {$ne: ''} arrive as objects from query params — [$ne]=x syntax).
 *  2. Format validation: UUID v4 pattern check before hitting the database.
 *     Rejects obviously invalid keys without a DB round-trip.
 *  3. Removed query-string fallback — API keys must be in the x-api-key header
 *     only. Query string keys appear in server access logs, CDN logs, and
 *     browser history — all bad places for a secret.
 */

const Company    = require('../models/Company');
const AppError   = require('../utils/AppError');
const catchAsync = require('../utils/catchAsync');

// UUID v4 pattern — all API keys generated by uuidv4() match this exactly
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

const resolveByApiKey = catchAsync(async (req, res, next) => {
  // SECURITY: only accept header, never query param
  // Query params appear in access logs, CDN logs, and browser history
  const apiKey = req.headers['x-api-key'];

  // SECURITY: typeof check prevents NoSQL injection via object operators
  // e.g. ?apiKey[$ne]=x sends { '$ne': 'x' } as an object, not a string
  if (!apiKey || typeof apiKey !== 'string') {
    return next(new AppError('API key required', 401));
  }

  // SECURITY: validate format before querying DB — rejects garbage without I/O
  if (!UUID_RE.test(apiKey.trim())) {
    return next(new AppError('Invalid API key format', 401));
  }

  const company = await Company.findOne({ apiKey: apiKey.trim() }).lean();
  if (!company) return next(new AppError('Invalid API key', 401));

  req.companyId = company._id;
  req.company   = company;
  next();
});

module.exports = { resolveByApiKey };
